### ISSUE TITLE
Unable to compile on EL8 - requires following patch

### ISSUE THREAD

**Issue by traxtopel** [lenovo/thinklmi#1]
diff -ur thinklmi-master.orig/thinklmi-kernel/think-lmi.c thinklmi-master/thinklmi-kernel/think-lmi.c
--- thinklmi-master.orig/thinklmi-kernel/think-lmi.c	2020-06-16 21:57:19.000000000 +0200
+++ thinklmi-master/thinklmi-kernel/think-lmi.c	2020-06-18 06:27:51.524903469 +0200
@@ -41,6 +41,7 @@
 #include <linux/fs.h>
 #include <linux/cdev.h>
 #include "think-lmi.h"
+#include <linux/version.h>
 
 #define	THINK_LMI_FILE	"think-lmi"
 
@@ -1581,7 +1582,11 @@
 	return 0;
 }
 
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 3, 0))
 static int think_lmi_probe(struct wmi_device *wdev, const void *context)
+#else
+static int think_lmi_probe(struct wmi_device *wdev)
+#endif
 {
 	return think_lmi_add(wdev);
 }

**Comment by mrhpearson** [comment]
Thanks! Patch implemented in e38641f
Mark
