### ISSUE TITLE
Userspace binary does not run without root priveleges

### ISSUE THREAD

**Issue by traxtopel** [lenovo/thinklmi#2]
diff -ur thinklmi-master.orig/thinklmi-user/thinklmi.c thinklmi-master/thinklmi-user/thinklmi.c
--- thinklmi-master.orig/thinklmi-user/thinklmi.c	2020-06-16 21:57:19.000000000 +0200
+++ thinklmi-master/thinklmi-user/thinklmi.c	2020-06-18 07:06:55.246944671 +0200
@@ -125,6 +125,10 @@
 
 int main(int argc, char *argv[])
 {
+   if (getuid()!=0) {
+    printf("Please run with administrator privileges\n");
+    exit(0);
+    }
     char *file_name = "/dev/thinklmi";
     int fd;
     enum {

**Comment by mrhpearson** [comment]
Thanks! Patch implemented in e38641f
Let me know if you see any other issues
Mark
