### ISSUE TITLE
"insmod" not persistent

### ISSUE THREAD

**Issue by GreLinz** [lenovo/thinklmi#4]
It's not possible to use thinklmi command after reboot. Need to execute "insmod" after each reboot to get thinklmi command to work.

------------------------------------------------------------------------------------------------------
ThinkStation P520 : BIOS 36A : Ubuntu 19.10 - 5.3.0-59
------------------------------------------------------------------------------------------------------

**Comment by zhanggyb** [comment]
Hi @GreLinz ,

The `insmod` command only loads the module file once and does not consider dependencies when doing so.

To auto-load the module you need to:

1. Put the `think-lmi.ko` in `/lib/modules/$(uname -r)`, `/lib/modules/$(uname -r)/extra/` or `/lib/modules/$(uname -r)/updates/` will be a good choice.
2. Run `sudo depmod`
3. Create a simple config file in `/etc/modules-load.d/`:
   ``` bash
   # /etc/modules-load.d/thinklmi.conf
   think-lmi
   ```

Note: when you upgrade your kernel package you need to do these steps again.

**Comment by mrhpearson** [comment]
Hi @zhanggyb 

I was thinking we should modify the Makefile to do these steps (under 'make install'?)

Long term we need to get this upstream :)

Mark

**Comment by mrhpearson** [comment]
Fixed by https://github.com/lenovo/thinklmi/pull/10/commits/3509baded89e91b99a9a859527dd99b093a51faf
