### ISSUE TITLE
Unable to modify Primary, Automatic, and Error Boot sequence

### ISSUE THREAD

**Issue by GreLinz** [lenovo/thinklmi#6]
In the list of thiniklmi getsettings the option to change boot sequence for Primary, Automatic, and Error boot sequence is not listed.

**Comment by mrhpearson** [comment]
Hi Gregor,

Which platform are you testing on? I think I need a bit more insight into what you mean by 'Boot sequence' too

On my P1G2 there is BootOrder:
[banther@localhost thinklmi-user]$ sudo ./thinklmi -g BootOrder
USBCD:USBFDD:NVMe0:NVMe1:HDD0:HDD1:USBHDD:PXEBOOT:HTTPSBOOT:LENOVOCLOUD
HDD0,HDD1,HDD2,HDD3,HDD4,PXEBOOT,ATAPICD0,ATAPICD1,ATAPICD2,USBFDD,USBCD,USBHDD,OtherHDD,OtherCD,NVMe0,NVMe1,NVMe2,HTTPSBOOT,LENOVOCLOUD,NODEV

Is that the kind of thing you are looking for? 

As a note - the settings that thinklmi can alter is only what is provided by the BIOS. If something is missing we'll have to work with the BIOS team to get it added. 

Thanks!
Mark

**Comment by GreLinz** [comment]
Hi Mark,

for verification I'm using a : ThinkStation P520 : BIOS 36A : Ubuntu 19.10 - 5.3.0-59

For desktop workstation the bios options differ to other systems, like P1G2.

We're supporting three boot options : PRIMARY, AUTOMATIC, and ERROR. Please see below the options taken from the previous WMI solution :
Primary Boot Sequence - USB FDD:USB KEY:VMD 1:VMD 2:VMD 3:M.2 Drive 1:M.2 Drive 2:PCIE SLOT 1:PCIE SLOT 2:PCIE SLOT 3:PCIE SLOT 4:PCIE SLOT 6:SATA 1:SATA 2:SATA 3:SATA 4:SATA 5:SATA 6:eSATA :Network 1:USB HDD:USB CDROM;[Excluded from boot order:PCI  SLOT 5:Network 2:Network 3:Network 4:Network 5]
Automatic Boot Sequence - Network 1:VMD 1:VMD 2:VMD 3:M.2 Drive 1:M.2 Drive 2:PCIE SLOT 1:PCIE SLOT 2:PCIE SLOT 3:PCIE SLOT 4:PCIE SLOT 6:SATA 1:SATA 2:SATA 3:SATA 4:SATA 5:SATA 6:eSATA ;[Excluded from boot order:PCI  SLOT 5:USB FDD:USB KEY:USB HDD:USB CDROM:Network 2:Network 3:Network 4:Network 5]
Error Boot Sequence - Network 1:VMD 1:VMD 2:VMD 3:M.2 Drive 1:M.2 Drive 2:PCIE SLOT 1:PCIE SLOT 2:PCIE SLOT 3:PCIE SLOT 4:PCIE SLOT 6:SATA 1:SATA 2:SATA 3:SATA 4:SATA 5:SATA 6:eSATA ;[Excluded from boot order:PCI  SLOT 5:USB FDD:USB 
KEY:USB HDD:USB CDROM:Network 2:Network 3:Network 4:Network 5]

Regards
Gregor

**Comment by JiqiLee** [comment]
> In the list of thiniklmi getsettings the option to change boot sequence for Primary, Automatic, and Error boot sequence is not listed.

It seems other tools  as srlin64 has supported for Thinkstation platfrom.

**Comment by JiqiLee** [comment]
I checked thinklmi driver code, and it used different way to communicate with BIOS.

**Comment by JiqiLee** [comment]
[bios_20200429.zip](https://github.com/lenovo/thinklmi/files/6127241/bios_20200429.zip)
I have some codes as modified from BIOS to support new BIOS mode on P-serials workstation.  Or you can check this from BIOS team.

**Comment by mrhpearson** [comment]
Hi @JiqiLee 

I deleted your previous post as I'm guessing you're a Lenovo employee and you just publicly posted a whole big blob of code that I'm pretty sure hasn't been through our open source review process. (If you're not a Lenovo employee then my sincere apologies).

It's awesome to contribute here, but I think what you were sharing isn't ready to be public yet, and had copyright headers on.

Please contact me on my Lenovo address (mpearson) and we can discuss the smi implementation - it certainly looked interesting, but I have some questions about what it is doing and how best to integrate it into thinkLMI.

Thanks! 
Mark

**Comment by JiqiLee** [comment]
Hi Mark,

Yes, understood. it seems to be thinklmi driver issue.
 I have added some debug code as follows:
`        /*
         * Try to find the number of valid settings of this machine
         * and use it to create sysfs attributes
         */
        for (i = 0; i < 0xFF; ++i) {
                char *item = NULL;
                int spleng = 0;
                int num = 0;
                char *p;

                status = think_lmi_setting(i, &item,
                                LENOVO_BIOS_SETTING_GUID);
                if (ACPI_FAILURE(status))
                        break;
                if (!item )
                        break;
                if (!*item)
                        continue;

                /* It is not allowed to have '/' for file name.
                 * Convert it into '\'. */
                spleng = strlen(item);
                for (num = 0; num < spleng; num++) {
                        if (item[num] == '/')
                                item[num] = '\\';
                }

                /* Remove the value part */
                p = strchr(item, ',');
                if (p)
                        *p = '\0';
                think->settings[i] = item; /* Cache setting name */
                think->settings_count++;

                **pr_info("%s>>>>idx: %d, item: %s", __func__, think->settings_count, item);**
        }

        {
                int i;
                for (i = 0; i < think->settings_count; i++)
                {
                        **pr_info("%s....idx: %d, item: %s", __func__, i, think->settings[i]);**
                }
        }`

And found strange results, although 'item' in the first loop is right string. However, the second loop will get wrong strings.
Attached for your referrence.

Regards,
Jiqi.

**Comment by sugudsl** [comment]
This issues is fixed now. Shall we close this

**Comment by mrhpearson** [comment]
This was fixed by https://github.com/lenovo/thinklmi/commit/2eaf1063aa71fbc1ade6fe840dd45fc1650aef48 right?
